name: log_time
description: A library to track the duration of an operation. Inspired by JavaScript's console.time and console.end.
version: 0.0.1
homepage: https://github.com/krgutierrez/time_logger

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
